/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BaseBreadcrumb: typeof import('./src/components/shared/BaseBreadcrumb.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    copy: typeof import('./src/components/shared/SelectPostOrder copy.vue')['default']
    CustomDatePicker: typeof import('./src/components/shared/Form/DatePicker/CustomDatePicker.vue')['default']
    CustomToggleSwitch: typeof import('./src/components/shared/CustomToggleSwitch.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    GridVirtualizerDynamic: typeof import('./src/components/tracking_report/GridVirtualizerDynamic.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hoso11h05: typeof import('./src/components/template/hoso/Hoso11h05.vue')['default']
    Hoso15h05: typeof import('./src/components/template/hoso/Hoso15h05.vue')['default']
    Hoso17h05: typeof import('./src/components/template/hoso/Hoso17h05.vue')['default']
    Hoso19h35: typeof import('./src/components/template/hoso/Hoso19h35.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Khmer: typeof import('./src/components/template/khmer/Khmer.vue')['default']
    KhmerYouTube: typeof import('./src/components/template/khmer_youtube/KhmerYouTube.vue')['default']
    LogoutDialog: typeof import('./src/components/layout/LogoutDialog.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectGroupTime: typeof import('./src/components/shared/SelectGroupTime.vue')['default']
    SelectPlatform: typeof import('./src/components/shared/SelectPlatform.vue')['default']
    SelectPostOrder: typeof import('./src/components/shared/SelectPostOrder.vue')['default']
    SelectSery: typeof import('./src/components/shared/SelectSery.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    SwitchToggle: typeof import('./src/components/shared/Form/SwitchToggle/SwitchToggle.vue')['default']
    Thinhnam10h30: typeof import('./src/components/template/thinhnam/Thinhnam10h30.vue')['default']
    Thinhnam13h30: typeof import('./src/components/template/thinhnam/Thinhnam13h30.vue')['default']
    Thinhnam19h30: typeof import('./src/components/template/thinhnam/Thinhnam19h30.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Vn4h30: typeof import('./src/components/template/vn/Vn4h30.vue')['default']
    VN4h30: typeof import('./src/components/template/vn/VN4h30.vue')['default']
    VN6h30: typeof import('./src/components/template/vn/VN6h30.vue')['default']
  }
  export interface GlobalDirectives {
    KeyFilter: typeof import('primevue/keyfilter')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
